# Generated by Django 3.0.8 on 2020-07-22 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200708_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='subscribed',
            field=models.ManyToManyField(related_name='subscribed_to_subr', to=settings.AUTH_USER_MODEL),
        ),
    ]
