# Generated by Django 3.0.8 on 2020-07-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='moderator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='subreddit.Moderator'),
        ),
    ]
