# Generated by Django 3.0.8 on 2020-07-08 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0002_auto_20200708_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='moderator',
        ),
        migrations.AddField(
            model_name='subreddit',
            name='moderator',
            field=models.ManyToManyField(default=None, related_name='moderator', to='subreddit.Moderator'),
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subreddit',
            name='subscriber',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
