# Generated by Django 3.0.8 on 2020-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0003_auto_20200708_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='moderator',
            field=models.ManyToManyField(related_name='moderator', to='subreddit.Moderator'),
        ),
    ]
