# Generated by Django 3.0.8 on 2020-07-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0005_remove_moderator_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
