# Generated by Django 3.0.8 on 2020-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0006_auto_20200714_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
