# Generated by Django 3.0.8 on 2020-07-21 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0007_auto_20200715_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowReddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_reddit', to='subreddit.SubReddit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reddit')},
            },
        ),
    ]
