# Generated by Django 3.0.8 on 2020-07-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0009_followreddit_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowReddit',
        ),
    ]
